name: B32Marketing
favicon: null
layout_spectrum: 0.2611716908868402
typography_spectrum: 0.11140883690677583
title: B32Marketing grid test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fbfbfb'
    - '#5c3119'
    - '#ff7247'
    - '#ffc7a8'
  brandStrength: 0.6935412930324674
  lightness: 0.326450229389593
  saturation: 0.02179934992454946
  rhythmicContrast: 0.9554215208627284
purpose: []
